apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    app.kubernetes.io/instance: ibm-crossplane-provider-kubernetes
    app.kubernetes.io/managed-by: ibm-crossplane-provider-kubernetes
    app.kubernetes.io/name: ibm-crossplane-provider-kubernetes
    name: ibm-crossplane-provider-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibm-crossplane-provider-kubernetes
      intent: projected
      release: ibm-crossplane-provider-kubernetes
  template:
    metadata:
      labels:
        app: ibm-crossplane-provider-kubernetes
        intent: projected
        release: ibm-crossplane-provider-kubernetes
        app.kubernetes.io/instance: ibm-crossplane-provider-kubernetes
        app.kubernetes.io/managed-by: ibm-crossplane-provider-kubernetes
        app.kubernetes.io/name: ibm-crossplane-provider-kubernetes
      annotations:
        productID: 068a62892a1e4db39641342e592daa25
        productMetric: FREE
        productName: IBM Cloud Platform Common Services
    spec:
      restartPolicy: Always
      serviceAccountName: ibm-crossplane-provider-kubernetes
      schedulerName: default-scheduler
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ibm-crossplane-provider-kubernetes
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: 50m
              memory: 256Mi
              ephemeral-storage: 5Mi
            requests:
              cpu: 25m
              memory: 128Mi
              ephemeral-storage: 5Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          name: ibm-crossplane-provider-kubernetes
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.targetNamespaces']
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          imagePullPolicy: Always
          volumeMounts:
            - name: package-cache
              mountPath: /cache
          image: icr.io/cpopen/ibm-crossplane-provider-kubernetes-operator:1.8.0
          args: []
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              key: app
              values: ibm-crossplane-provider-kubernetes
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/region
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              key: app
              values: ibm-crossplane-provider-kubernetes
      serviceAccount: ibm-crossplane-provider-kubernetes
      volumes:
        - name: package-cache
          emptyDir:
            sizeLimit: 5Mi
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
