kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-crossplane
  labels:
    app.kubernetes.io/instance: ibm-crossplane-provider-kubernetes
    app.kubernetes.io/managed-by: ibm-crossplane-provider-kubernetes
    app.kubernetes.io/name: ibm-crossplane-provider-kubernetes
rules:
  - verbs:
      - list
      - watch
      - update
    apiGroups:
      - kubernetes.crossplane.io
    resources:
      - objects
      - objects/status
      - providerconfigs
      - providerconfigs/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - kubernetes.crossplane.io
    resources:
      - providerconfigusages
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - update
      - patch
      - delete