# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- ./bases/kubernetes.crossplane.io_objects.yaml
- ./bases/kubernetes.crossplane.io_providerconfigs.yaml
- ./bases/kubernetes.crossplane.io_providerconfigusages.yaml
# +kubebuilder:scaffold:crdkustomizeresource

commonLabels:
  app.kubernetes.io/instance: ibm-crossplane-operator
  app.kubernetes.io/managed-by: ibm-crossplane-operator
  app.kubernetes.io/name: ibm-crossplane
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
